server:
  port: 8001
#mybatis 配置
mybatis:
  type-aliases-package: com.listron.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring 配置
spring:
  application:
    name: springcloud-provider-dept  #3 个名字相同是前提
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#服务注册到eureka中

eureka:
  client:
    service-url:
      #发不到7001、7002、7003集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept-hystrix-01
info:
  app.name: listron-springcloud
  company.name: baidu.com